// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/gw-gong/gwkit-go/hotcfg"
	"github.com/gw-gong/key-spy/internal/app/scanner/crawler"
	"github.com/gw-gong/key-spy/internal/app/scanner/notifier"
	"github.com/gw-gong/key-spy/internal/app/scanner/reporter"
	"github.com/gw-gong/key-spy/internal/app/scanner/service"
	"github.com/gw-gong/key-spy/internal/config/scanner/localcfg"
)

// Injectors from wire.go:

func InitServer(cfgOption *hotcfg.LocalConfigOption) (*Server, func(), error) {
	config, err := localcfg.NewConfig(cfgOption)
	if err != nil {
		return nil, nil, err
	}
	hotLoaderManager := hotcfg.NewHotLoaderManager()
	crawlerCrawler := crawler.NewCrawler(config)
	reporterReporter := reporter.NewReporter(config)
	notifierNotifier := notifier.NewNotifier(config)
	scannerService := service.NewScannerService(config, crawlerCrawler, reporterReporter, notifierNotifier)
	server := &Server{
		cfg:            config,
		hlm:            hotLoaderManager,
		scannerService: scannerService,
	}
	return server, func() {
	}, nil
}

// wire.go:

var ConfigSet = wire.NewSet(localcfg.NewConfig, hotcfg.NewHotLoaderManager)

var BizSet = wire.NewSet(crawler.NewCrawler, reporter.NewReporter, notifier.NewNotifier, service.NewScannerService)

var ServerSet = wire.NewSet(wire.Struct(new(Server), "*"))
